language: node_js
node_js: 14

services: docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-api-feed leonista/udagram-api-feed:v1.0.0
  - docker tag udagram-api-user leonista/udagram-api-user:v1.0.0
  - docker tag reverseproxy leonista/reverseproxy:v1.0.0
  - docker tag udagram-frontend leonista/udagram-frontend:v1.0.0

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push leonista/udagram-api-feed:v1.0.0
  - docker push leonista/udagram-api-user:v1.0.0
  - docker push leonista/reverseproxy:v1.0.0
  - docker push leonista/udagram-frontend:v1.0.0